default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>

development:
  <<: *default
  database: amoedo_app_development

test:
  <<: *default
  database: amoedo_app_test

production:
  primary: &primary_production
    <<: *default
    database: amoedo_app_production
    username: <%= ENV["AMOEDO_DB_USER"] %>
    password: <%= ENV["AMOEDO_USER_PASSWORD"] %>
    host: <%= ENV["AMOEDO_DB_HOST"] %>
  # Keep your existing production configuration for multiple databases
  cache:
    <<: *primary_production
    database: amoedo_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: amoedo_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: amoedo_app_production_cable
    migrations_paths: db/cable_migrate

